apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visitor-counter
  template:
    metadata:
      labels:
        app: visitor-counter
    spec:
      containers:
      - name: visitor-counter
        image: rodrigo-perin/visitor-counter:latest
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: DYNAMODB_TABLE
          value: "VisitorCounter"
        ports:
        - containerPort: 5000
