apiVersion: v1
kind: Service
metadata:
  name: visitor-counter-service
spec:
  selector:
    app: visitor-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
